
/* Insert Statements ************ */

--Game Table
insert into dbo.game(gamename, gamedescription, cost, howtoplay, numberofballs, isspecial) values ('Powerball', 'Powerball is America’s favorite game for a reason—millions upon millions of reasons, actually. Jackpots start at $40 million but can grow to hundreds of millions or more. Tickets are $2. Join in on the fun!', 2,'Leave it all up to luck and ask for a Powerball quick pick. Or, choose your own numbers. Pick five numbers from 1–69 and one Powerball number from 1–26. Play slips are available at lottery retailers. There are nine ways to win, starting with $4 for matching just the Powerball. Match the first five numbers plus the Powerball to win the jackpot. Your ticket could be worth millions of dollars—sign the back right away!',5,'Y');
insert into dbo.game(gamename, gamedescription, cost, howtoplay, numberofballs, isspecial) values ('Mega Millions', 'If you answered, “being a mega-millionaire” the last time someone asked what your dream job is, Mega Millions might be the game for you. Jackpots start at $15 million and tickets are only a buck.', 1,'Leave it all up to luck and ask for a Mega Millions quick pick. Or, choose your own numbers. Pick five numbers from 1–75 and one Mega Ball number from 1–15. Play slips are available at lottery retailers. There are nine ways to win, starting with $1 for matching just the Mega Ball. Match the first five numbers plus the Mega Ball to win the jackpot. Your ticket could be worth millions of dollars—sign the back right away!',5,'Y');
insert into dbo.game(gamename, gamedescription, cost, howtoplay, numberofballs, isspecial) values ('Gopher 5', 'The Twins, Jolly Green Giant, and six-month winters: some of the best things are only available in Minnesota. Gopher 5 is one of those things. It only takes $1 to play for jackpots that start at $100,000.', 1,'Leave it all up to luck and ask for a Gopher 5 quick pick. Or choose your own numbers. Pick five numbers from 1 – 47. Play slips are available at lottery retailers. Win by matching two, three, four or five numbers. Match all five to win the jackpot. Sign the back of your ticket right away; in a day or two, it could be worth $100,000 or more!',5,'');
insert into dbo.game(gamename, gamedescription, cost, howtoplay, numberofballs, isspecial) values ('Northstar Cash', 'Northstar Cash offers the best odds of any of our jackpot lotto games. Everyone knows that the North Star is the luckiest star so it’s no surprise that so many players have had stellar luck with this game. On average, the jackpot is won once every week. Jackpots start at $25,000 and sometimes grow into the six-digit territory.', 1,'Leave it all up to luck and ask for a Northstar Cash quick pick. Or choose your own numbers. Pick five numbers from 1–31. Play slips are available at lottery retailers. Win by matching two, three, four or five numbers. Match all five to win the jackpot. Your ticket could be worth a lot of money—sign the back right away!',5,'');


--MatchOddsWinnings
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('Powerball ONLY','1 in 38','4',1);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('1 of 5 + Powerball','1 in 92','4',1);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('2 of 5 + Powerball','1 in 701','7',1);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('3 of 5 numbers','1 in 580','7',1);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('3 of 5 + Powerball','1 in 14,494','100',1);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('4 of 5 numbers','1 in 36,525','100',1);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('4 of 5 + Powerball','1 in 913,129','50000',1);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('5 of 5 numbers','1 in 11,688,054','1000000',1);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('5 of 5 + Powerball','1 in 292,201,338','Jackpot',1);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('Mega Ball ONLY','1 in 21','1',2);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('1 of 5 + Mega Ball','1 in 56','2',2);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('2 of 5 + Mega Ball','1 in 473','5',2);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('3 of 5','1 in 766','5',2);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('3 of 5 + Mega Ball','1 in 10,720','50',2);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('4 of 5','1 in 52,835','500',2);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('4 of 5 + Mega Ball','1 in 739,688','5000',2);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('5 of 5','1 in 18,492,204','1000000',2);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('5 of 5 + Mega Ball','1 in 258,890,850','Jackpot',2);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('2 of 5','1 in 13','1',3);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('3 of 5','1 in 178','15',3);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('4 of 5','1 in 7,304','500',3);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('5 of 5','1 in 1,533,939','Jackpot',3);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('2 of 5 numbers','1 in 7','1',4);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('3 of 5 numbers','1 in 52','5',4);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('4 of 5 numbers','1 in 1,307','50',4);
insert into dbo.matchoddswinnings(match, odds, winnings, gameid) values('5 of 5 numbers','1 in 169,911','Jackpot',4);


--Drawing
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/4/2013',81000000,1);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/7/2013',100000000,1);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/11/2013',122000000,1);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/14/2013',40000000,1);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/3/2013',257000000,2);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/6/2013',291000000,2);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/10/2013',344000000,2);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/13/2013',425000000,2);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/2/2013',260000,3);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/4/2013',280000,3);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/6/2013',320000,3);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/9/2013',365000,3);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/11/2013',415000,3);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/13/2013',100000,3);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/1/2013',30000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/2/2013',25000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/3/2013',26000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/4/2013',27000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/5/2013',28000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/6/2013',29000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/7/2013',30000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/8/2013',34000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/9/2013',25000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/10/2013',26000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/11/2013',25000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/12/2013',26000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/13/2013',27000,4);
insert into dbo.drawing(drawingdate,jackpot,gameid) values('12/14/2013',25000,4);



--WinningNumber (not yet inserted)
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (6,1,1);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (9,1,1);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (1,1,1);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (31,1,1);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (44,1,1);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (25,2,1);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (13,1,2);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (20,1,2);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (32,1,2);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (45,1,2);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (48,1,2);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (17,2,2);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (1,1,3);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (10,1,3);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (13,1,3);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (18,1,3);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (19,1,3);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (27,2,3);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (14,1,4);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (25,1,4);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (32,1,4);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (33,1,4);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (41,1,4);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (34,2,4);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (7,1,5);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (12,1,5);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (41,1,5);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (44,1,5);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (59,1,5);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (3,3,5);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (11,1,6);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (29,1,6);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (44,1,6);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (63,1,6);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (64,1,6);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (3,3,6);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (5,1,7);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (12,1,7);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (22,1,7);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (41,1,7);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (65,1,7);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (13,3,7);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (19,1,8);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (24,1,8);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (26,1,8);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (27,1,8);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (70,1,8);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (12,3,8);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (3,1,9);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (14,1,9);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (26,1,9);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (28,1,9);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (32,1,9);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (1,1,10);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (17,1,10);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (35,1,10);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (45,1,10);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (47,1,10);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (1,1,11);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (4,1,11);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (7,1,11);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (10,1,11);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (29,1,11);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (3,1,12);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (21,1,12);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (23,1,12);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (40,1,12);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (43,1,12);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (10,1,13);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (25,1,13);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (31,1,13);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (39,1,13);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (46,1,13);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (18,1,14);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (24,1,14);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (42,1,14);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (46,1,14);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (47,1,14);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (24,1,15);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (26,1,15);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (27,1,15);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (28,1,15);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (31,1,15);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (4,1,16);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (7,1,16);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (9,1,16);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (28,1,16);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (29,1,16);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (1,1,17);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (2,1,17);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (7,1,17);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (19,1,17);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (23,1,17);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (6,1,18);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (13,1,18);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (15,1,18);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (21,1,18);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (28,1,18);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (6,1,19);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (15,1,19);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (19,1,19);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (27,1,19);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (28,1,19);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (10,1,20);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (11,1,20);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (20,1,20);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (25,1,20);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (29,1,20);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (10,1,21);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (13,1,21);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (15,1,21);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (17,1,21);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (24,1,21);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (2,1,22);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (3,1,22);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (10,1,22);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (15,1,22);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (26,1,22);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (10,1,23);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (13,1,23);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (14,1,23);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (15,1,23);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (20,1,23);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (3,1,24);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (5,1,24);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (12,1,24);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (21,1,24);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (30,1,24);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (4,1,25);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (14,1,25);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (16,1,25);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (19,1,25);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (25,1,25);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (1,1,26);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (8,1,26);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (12,1,26);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (24,1,26);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (29,1,26);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (2,1,27);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (10,1,27);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (13,1,27);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (16,1,27);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (24,1,27);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (7,1,28);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (15,1,28);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (18,1,28);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (21,1,28);
insert into dbo.winningnumber(winningnumber, balltypeid, drawingid) values (24,1,28);


--BallType
insert into dbo.balltype(ballname) values('Normal');
insert into dbo.balltype(ballname) values('Powerball');
insert into dbo.balltype(ballname) values('Mega Ball');


--GameState
insert into dbo.gamestate(gameid,stateid) values(1,3);
insert into dbo.gamestate(gameid,stateid) values(1,4);
insert into dbo.gamestate(gameid,stateid) values(1,5);
insert into dbo.gamestate(gameid,stateid) values(1,6);
insert into dbo.gamestate(gameid,stateid) values(1,7);
insert into dbo.gamestate(gameid,stateid) values(1,8);
insert into dbo.gamestate(gameid,stateid) values(1,9);
insert into dbo.gamestate(gameid,stateid) values(1,10);
insert into dbo.gamestate(gameid,stateid) values(1,12);
insert into dbo.gamestate(gameid,stateid) values(1,13);
insert into dbo.gamestate(gameid,stateid) values(1,14);
insert into dbo.gamestate(gameid,stateid) values(1,15);
insert into dbo.gamestate(gameid,stateid) values(1,16);
insert into dbo.gamestate(gameid,stateid) values(1,17);
insert into dbo.gamestate(gameid,stateid) values(1,18);
insert into dbo.gamestate(gameid,stateid) values(1,19);
insert into dbo.gamestate(gameid,stateid) values(1,20);
insert into dbo.gamestate(gameid,stateid) values(1,21);
insert into dbo.gamestate(gameid,stateid) values(1,22);
insert into dbo.gamestate(gameid,stateid) values(1,23);
insert into dbo.gamestate(gameid,stateid) values(1,25);
insert into dbo.gamestate(gameid,stateid) values(1,26);
insert into dbo.gamestate(gameid,stateid) values(1,27);
insert into dbo.gamestate(gameid,stateid) values(1,29);
insert into dbo.gamestate(gameid,stateid) values(1,30);
insert into dbo.gamestate(gameid,stateid) values(1,31);
insert into dbo.gamestate(gameid,stateid) values(1,32);
insert into dbo.gamestate(gameid,stateid) values(1,33);
insert into dbo.gamestate(gameid,stateid) values(1,34);
insert into dbo.gamestate(gameid,stateid) values(1,35);
insert into dbo.gamestate(gameid,stateid) values(1,36);
insert into dbo.gamestate(gameid,stateid) values(1,37);
insert into dbo.gamestate(gameid,stateid) values(1,38);
insert into dbo.gamestate(gameid,stateid) values(1,39);
insert into dbo.gamestate(gameid,stateid) values(1,40);
insert into dbo.gamestate(gameid,stateid) values(1,41);
insert into dbo.gamestate(gameid,stateid) values(1,42);
insert into dbo.gamestate(gameid,stateid) values(1,43);
insert into dbo.gamestate(gameid,stateid) values(1,45);
insert into dbo.gamestate(gameid,stateid) values(1,46);
insert into dbo.gamestate(gameid,stateid) values(1,47);
insert into dbo.gamestate(gameid,stateid) values(1,48);
insert into dbo.gamestate(gameid,stateid) values(1,49);
insert into dbo.gamestate(gameid,stateid) values(1,50);
insert into dbo.gamestate(gameid,stateid) values(1,51);
insert into dbo.gamestate(gameid,stateid) values(1,52);
insert into dbo.gamestate(gameid,stateid) values(1,53);
insert into dbo.gamestate(gameid,stateid) values(2,3);
insert into dbo.gamestate(gameid,stateid) values(2,4);
insert into dbo.gamestate(gameid,stateid) values(2,5);
insert into dbo.gamestate(gameid,stateid) values(2,6);
insert into dbo.gamestate(gameid,stateid) values(2,7);
insert into dbo.gamestate(gameid,stateid) values(2,8);
insert into dbo.gamestate(gameid,stateid) values(2,9);
insert into dbo.gamestate(gameid,stateid) values(2,10);
insert into dbo.gamestate(gameid,stateid) values(2,12);
insert into dbo.gamestate(gameid,stateid) values(2,13);
insert into dbo.gamestate(gameid,stateid) values(2,14);
insert into dbo.gamestate(gameid,stateid) values(2,15);
insert into dbo.gamestate(gameid,stateid) values(2,16);
insert into dbo.gamestate(gameid,stateid) values(2,17);
insert into dbo.gamestate(gameid,stateid) values(2,18);
insert into dbo.gamestate(gameid,stateid) values(2,19);
insert into dbo.gamestate(gameid,stateid) values(2,20);
insert into dbo.gamestate(gameid,stateid) values(2,21);
insert into dbo.gamestate(gameid,stateid) values(2,22);
insert into dbo.gamestate(gameid,stateid) values(2,23);
insert into dbo.gamestate(gameid,stateid) values(2,25);
insert into dbo.gamestate(gameid,stateid) values(2,26);
insert into dbo.gamestate(gameid,stateid) values(2,27);
insert into dbo.gamestate(gameid,stateid) values(2,29);
insert into dbo.gamestate(gameid,stateid) values(2,30);
insert into dbo.gamestate(gameid,stateid) values(2,31);
insert into dbo.gamestate(gameid,stateid) values(2,32);
insert into dbo.gamestate(gameid,stateid) values(2,33);
insert into dbo.gamestate(gameid,stateid) values(2,34);
insert into dbo.gamestate(gameid,stateid) values(2,35);
insert into dbo.gamestate(gameid,stateid) values(2,36);
insert into dbo.gamestate(gameid,stateid) values(2,37);
insert into dbo.gamestate(gameid,stateid) values(2,38);
insert into dbo.gamestate(gameid,stateid) values(2,39);
insert into dbo.gamestate(gameid,stateid) values(2,40);
insert into dbo.gamestate(gameid,stateid) values(2,41);
insert into dbo.gamestate(gameid,stateid) values(2,42);
insert into dbo.gamestate(gameid,stateid) values(2,43);
insert into dbo.gamestate(gameid,stateid) values(2,45);
insert into dbo.gamestate(gameid,stateid) values(2,46);
insert into dbo.gamestate(gameid,stateid) values(2,47);
insert into dbo.gamestate(gameid,stateid) values(2,48);
insert into dbo.gamestate(gameid,stateid) values(2,49);
insert into dbo.gamestate(gameid,stateid) values(2,50);
insert into dbo.gamestate(gameid,stateid) values(2,51);
insert into dbo.gamestate(gameid,stateid) values(2,53);
insert into dbo.gamestate(gameid,stateid) values(3,23);
insert into dbo.gamestate(gameid,stateid) values(4,23);


--State
insert into dbo.state(statename) values('Alabama');
insert into dbo.state(statename) values('Alaska');
insert into dbo.state(statename) values('Arizona');
insert into dbo.state(statename) values('Arkansas');
insert into dbo.state(statename) values('California');
insert into dbo.state(statename) values('Colorado');
insert into dbo.state(statename) values('Connecticut');
insert into dbo.state(statename) values('Delaware');
insert into dbo.state(statename) values('Florida');
insert into dbo.state(statename) values('Georgia');
insert into dbo.state(statename) values('Hawaii');
insert into dbo.state(statename) values('Idaho');
insert into dbo.state(statename) values('Illinois');
insert into dbo.state(statename) values('Indiana');
insert into dbo.state(statename) values('Iowa');
insert into dbo.state(statename) values('Kansas');
insert into dbo.state(statename) values('Kentucky');
insert into dbo.state(statename) values('Louisiana');
insert into dbo.state(statename) values('Maine');
insert into dbo.state(statename) values('Maryland');
insert into dbo.state(statename) values('Massachusetts');
insert into dbo.state(statename) values('Michigan');
insert into dbo.state(statename) values('Minnesota');
insert into dbo.state(statename) values('Mississippi');
insert into dbo.state(statename) values('Missouri');
insert into dbo.state(statename) values('Montana');
insert into dbo.state(statename) values('Nebraska');
insert into dbo.state(statename) values('Nevada');
insert into dbo.state(statename) values('New Hampshire');
insert into dbo.state(statename) values('New Jersey');
insert into dbo.state(statename) values('New Mexico');
insert into dbo.state(statename) values('New York');
insert into dbo.state(statename) values('North Carolina');
insert into dbo.state(statename) values('North Dakota');
insert into dbo.state(statename) values('Ohio');
insert into dbo.state(statename) values('Oklahoma');
insert into dbo.state(statename) values('Oregon');
insert into dbo.state(statename) values('Pennsylvania');
insert into dbo.state(statename) values('Rhode Island');
insert into dbo.state(statename) values('South Carolina');
insert into dbo.state(statename) values('South Dakota');
insert into dbo.state(statename) values('Tennessee');
insert into dbo.state(statename) values('Texas');
insert into dbo.state(statename) values('Utah');
insert into dbo.state(statename) values('Vermont');
insert into dbo.state(statename) values('Virginia');
insert into dbo.state(statename) values('Washington');
insert into dbo.state(statename) values('West Virginia');
insert into dbo.state(statename) values('Wisconsin');
insert into dbo.state(statename) values('Wyoming');
insert into dbo.state(statename) values('Washington D.C.');
insert into dbo.state(statename) values('Puerto Rico');
insert into dbo.state(statename) values('U.S. Virgin Islands');